# Generated by go2rpm 1
%bcond_without check

# https://github.com/serenize/snaker
%global goipath         github.com/serenize/snaker
%global commit          a683aaf2d516deecd70cad0c72e3ca773ecfcef0

%gometa

%global common_description %{expand:
This is a small utility to convert camel cased strings to snake case and back,
except some defined words.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        This is a small utility to convert camel cased strings to snake case and back, except some defined words

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/onsi/ginkgo)
BuildRequires:  golang(github.com/onsi/gomega)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Jan 25 16:22:34 CET 2020 Marcel Metz <mmetz@adrian-broher.net> - 0-0.1.20200125gita683aaf
- Initial package
